# Generated by Django 5.1.2 on 2024-10-14 19:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
