# Generated by Django 5.1.2 on 2024-10-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_alter_game_description_alter_story_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
